[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[scheduled.functions]]
  name = "schedule-rotate-keys"
  schedule = "0 3 1 */3 *" # trimestral: día 1 a las 03:00

[[scheduled.functions]]
  name = "schedule-backup-restore-check"
  schedule = "0 2 * * *"   # diario: 02:00 UTC